apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
  - secret.yaml
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: webapp-deployment
