apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: webapp-deployment

configMapGenerator:
  - name: staging-config
    literals:
      - LOG_LEVEL=INFO
      - FEATURE_FLAG=false

secretGenerator:
  - name: staging-secret
    literals:
      - DB_PASSWORD=stagingPassword456
      - API_KEY=stagingApiKey789

generatorOptions:
  disableNameSuffixHash: true

