name: Deploy WebApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: 5.7.1

      - name: Configure kubeconfig from secret
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Deploy to Development Environment
        run: kubectl apply -k overlays/dev

      - name: Deploy to Staging Environment
        if: github.ref == 'refs/heads/main'
        run: kubectl apply -k overlays/staging

      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/main'
        run: kubectl apply -k overlays/production
